[build-system]
requires = ['setuptools>=61.0']
build-backend = 'setuptools.build_meta'

[project]
name = 'metric-money'
version = '0.0.1'
authors = [
  { name='Brad Corlett', email='admin@medium.technology' },
]
description = 'mspec application generator and browsing protocol'
readme = 'README.md'
requires-python = '>=3.7'
dependencies = [
	'beautifulsoup4',
	'matplotlib',
]
license = 'MIT'
